### GET-request för att hämta alla todos
GET http://localhost:3000/

### POST-request för att skapa en ny todo
POST http://localhost:3000/api/post
Content-Type: application/json

{
    "title": "Koda",
    "completed": false
}

### PUT-request för att markera en todo som completed
PUT http://localhost:3000/api/todos/66827f4c23ff990ccb674e56/complete
Content-Type: application/json

### DELETE-request för att ta bort en todo
DELETE http://localhost:3000/api/delete/


